feat(cmd): Add support for registry operations
oasisprotocol/cli pull request #47
Opened 2023-03-28 17:05 UTC by kostko

2023-03-29 15:02 UTC, matevz requested changes
Few questions:
1. Where is nodeRegister operation?
2. Should we move `oasis inspect registry` to something like `oasis registry show` instead? Also`oasis registry dump` would come in handy.

2023-03-29 15:02 UTC, matevz commented on cmd/registry.go
> +
I usually group core and sdk together.

```suggestion
```

2023-03-29 20:04 UTC, kostko commented
Node registration happens automatically by oasis-node so manual registration should never be needed.

Good point about the registry inspect functions. By dump you probably mean something like the current `inspect registry nodes`?

2023-03-30 10:09 UTC, kostko commented on cmd/registry.go
> +
Fixed.

2023-03-30 10:10 UTC, kostko commented
Moved the `inspect registry` part as well.

2023-03-30 14:56 UTC, matevz approved these changes
Good job!

2023-03-30 14:56 UTC, matevz commented on cmd/registry.go
> +				cobra.CheckErr(fmt.Errorf("entity ID (%s) does not correspond to selected account (%s)",
```suggestion
				cobra.CheckErr(fmt.Errorf("entity ID '%s' does not correspond to selected account '%s' (%s)",
```

2023-03-30 14:56 UTC, matevz commented on cmd/registry.go
> +					descriptor.ID, signer.Public()))
```suggestion
					descriptor.ID, npa.AccountName, signer.Public()))
```

2023-03-30 14:56 UTC, matevz commented on cmd/registry.go
> +				cobra.CheckErr("account does not support signing consensus transactions")
```suggestion
				cobra.CheckErr(fmt.Errorf("account '%s' does not support signing consensus transactions", npa.AccountName))
```

2023-03-30 14:56 UTC, matevz commented on cmd/registry.go
> +			sigTx, err := common.SignConsensusTransaction(ctx, npa, acc, conn, tx)
It would be nice if PrettyPrinter omitted the

```
Body:
  {}
```

chunk if Body is empty. But this needs to be fixed in SDK.

2023-03-30 14:56 UTC, matevz commented on cmd/registry.go
> +	registryShowCmd.Flags().AddFlagSet(common.SelectorFlags)
`oasis registry show`  only requires `--network` flag afaik.

2023-03-30 14:56 UTC, merged

2023-03-30 14:58 UTC, matevz commented
Ah, crap, automerge was enabled. Can you make a short followup?

2023-03-30 17:29 UTC, kostko commented
Yeah will do.

2023-03-30 17:36 UTC, kostko commented
@matevz should be addressed in #49.